version: '3.8'
services:
  mysqldb:
    container_name: legacyqc-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/mysql/data
    networks:
      - app-network

  nextjs:
    container_name: legacyqc-app
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'mysql://root:1234@localhost:3306/DATABASE'
      NEXT_PUBLIC_PRISMA_URL: "mysql://root:1234@mysqldb:3306/DATABASE"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: 'bSCqOJA8QQ7UkWvqf8Mkf3LwthTGxvqaKip2NTfzN2g='
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data: