import Head from "next/head";
import { Navbar, Dashboard } from "../../src/components/index";
import { useSession } from "next-auth/react";
import { Box, Button } from "@mui/material";
import Link from "next/link";

export default function adminDashboard() {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>The LegacyQC App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Box>
          <Navbar />
          <Dashboard />
        </Box>
      </main>
    </>
  );
}
