import { Box } from "@mui/material";
import { Navbar, Dashboard } from "../../src/components";
import Head from "next/head";

export default function adminDashboard() {
  return (
    <>
      <Head>
        <title>LegacyQC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Box>
          <Navbar />
          <Dashboard />
        </Box>
      </main>
    </>
  );
}
