import Head from "next/head";
import { NavBar, Dashboard } from "../src/components/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>The LegacyQC App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Dashboard />
      </main>
    </>
  );
}
