import Head from "next/head";
import header from "../src/components/header/header";
import { Header, Dashboard } from "../src/components/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>LegacyQC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        <Dashboard />
      </main>
    </>
  );
}
